In [109]:
## Pandas
import pandas as pd
## Numpy
import numpy as np
## MatplotLib
import matplotlib.pyplot as plt
## Seaborn
import seaborn as sns

## Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_selector 
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer

## Models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

## Classification Metrics
from sklearn.metrics import (roc_auc_score, ConfusionMatrixDisplay, 
                             PrecisionRecallDisplay, RocCurveDisplay, 
                             f1_score, accuracy_score, classification_report)

## Set global scikit-learn configuration 
from sklearn import set_config
## Display estimators as a diagram
set_config(display='diagram') # 'text' or 'diagram'}
# new libraries
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [89]:
df = pd.read_csv('/content/database.csv')
df.head()

,Institution Name,Main Office,Branch Name,Branch Number,Established Date,Acquired Date,Street Address,City,County,State,Zipcode,Latitude,Longitude,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
0,JPMorgan Chase Bank,1,JPMorgan Chase Bank Main Office,0,01/01/1824,NaN,1111 Polaris Parkway,Columbus,Delaware,OH,43240,40.14453,-82.99115,633131000.0,743268000.0,832455000.0,916543000.0,1.032549e+09,1.069425e+09,1155185000
1,JPMorgan Chase Bank,0,Vernon Hills Scarsdale Branch,2,03/20/1961,NaN,676 White Plains Road,Scarsdale,Westchester,NY,10583,40.97008,-73.80670,293229.0,310791.0,325742.0,327930.0,3.277920e+05,3.414750e+05,381558
2,JPMorgan Chase Bank,0,Great Neck Northern Boulevard Branch,3,09/09/1963,NaN,410 Northern Boulevard,Great Neck,Nassau,NY,11021,40.77944,-73.72240,191011.0,206933.0,216439.0,237983.0,2.341830e+05,2.624550e+05,278940
3,JPMorgan Chase Bank,0,North Hartsdale Branch,4,02/19/1966,NaN,353 North Central Avenue,Hartsdale,Westchester,NY,10530,41.02654,-73.79168,87110.0,88367.0,93163.0,109659.0,1.119850e+05,1.167720e+05,140233
4,JPMorgan Chase Bank,0,Lawrence Rockaway Branch,5,01/16/1965,NaN,335 Rockaway Turnpike,Lawrence,Nassau,NY,11559,40.62715,-73.73675,172608.0,172749.0,189413.0,198445.0,2.051980e+05,2.232000e+05,235594

In [90]:
eda_ml = df.copy()

In [91]:
eda_ml.isna().sum()

Institution Name       0
Main Office            0
Branch Name            0
Branch Number          0
Established Date       0
Acquired Date       1615
Street Address         0
City                   0
County                 0
State                  0
Zipcode                0
Latitude              66
Longitude             66
2010 Deposits        740
2011 Deposits        578
2012 Deposits        329
2013 Deposits        175
2014 Deposits         56
2015 Deposits         19
2016 Deposits          0
dtype: int64

In [92]:
eda_ml.duplicated().sum()

0

In [93]:
eda_ml.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5413 entries, 0 to 5412
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Institution Name  5413 non-null   object
 1   Main Office       5413 non-null   int64
 2   Branch Name       5413 non-null   object
 3   Branch Number     5413 non-null   int64
 4   Established Date  5413 non-null   object
 5   Acquired Date     3798 non-null   object
 6   Street Address    5413 non-null   object
 7   City              5413 non-null   object
 8   County            5413 non-null   object
 9   State             5413 non-null   object
 10  Zipcode           5413 non-null   int64
 11  Latitude          5347 non-null   float64
 12  Longitude         5347 non-null   float64
 13  2010 Deposits     4673 non-null   float64
 14  2011 Deposits     4835 non-null   float64
 15  2012 Deposits     5084 non-null   float64
 16  2013 Deposits     5238 non-null   float64
 17  2014 Deposits     5357 non-null   float64
 18  2015 Deposits     5394 non-null   float64
 19  2016 Deposits     5413 non-null   int64
dtypes: float64(8), int64(4), object(8)
memory usage: 845.9+ KB

In [94]:
eda_ml.describe(include='all')

,Institution Name,Main Office,Branch Name,Branch Number,Established Date,Acquired Date,Street Address,City,County,State,Zipcode,Latitude,Longitude,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
count,5413,5413.000000,5413,5413.000000,5413,3798,5413,5413,5413,5413,5413.000000,5347.000000,5347.000000,4.673000e+03,4.835000e+03,5.084000e+03,5.238000e+03,5.357000e+03,5.394000e+03,5.413000e+03
unique,1,NaN,5317,NaN,3237,18,5375,1880,376,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,JPMorgan Chase Bank,NaN,Riverside Branch,NaN,01/01/1919,11/13/2004,66 Main Street,New York City,Los Angeles,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,5413,NaN,4,NaN,138,1602,3,154,298,1003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,0.000185,NaN,4303.761685,NaN,NaN,NaN,NaN,NaN,NaN,58800.016072,37.248922,-95.206261,2.668657e+05,3.037544e+05,3.234610e+05,3.462343e+05,3.819853e+05,3.935169e+05,4.268188e+05
std,NaN,0.013592,NaN,2146.930304,NaN,NaN,NaN,NaN,NaN,NaN,30863.015686,5.430381,17.542081,9.568755e+06,1.110829e+07,1.211339e+07,1.312320e+07,1.461318e+07,1.507385e+07,1.632941e+07
min,NaN,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,2110.000000,0.000000,-124.421370,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,NaN,0.000000,NaN,2548.000000,NaN,NaN,NaN,NaN,NaN,NaN,33334.000000,33.277225,-115.163740,2.252600e+04,2.315750e+04,2.465125e+04,2.689250e+04,2.935500e+04,3.394100e+04,3.951300e+04
50%,NaN,0.000000,NaN,4274.000000,NaN,NaN,NaN,NaN,NaN,NaN,60654.000000,38.939520,-88.442410,4.307200e+04,4.442600e+04,4.717350e+04,5.041500e+04,5.450300e+04,6.013350e+04,6.815700e+04
75%,NaN,0.000000,NaN,6172.000000,NaN,NaN,NaN,NaN,NaN,NaN,89102.000000,41.040635,-81.418135,8.502700e+04,8.614700e+04,9.000850e+04,9.506875e+04,1.023300e+05,1.115678e+05,1.243180e+05
max,NaN,1.000000,NaN,7989.000000,NaN,NaN,NaN,NaN,NaN,NaN,99362.000000,48.844760,0.000000,6.331310e+08,7.432680e+08,8.324550e+08,9.165430e+08,1.032549e+09,1.069425e+09,1.155185e+09

# Validation Split Data

In [95]:
X = eda_ml[['Institution Name','Main Office','City','Branch Number','Established Date','Acquired Date','Branch Name','Street Address','County','State','Zipcode','Latitude','Longitude','2010 Deposits','2011 Deposits','2012 Deposits','2013 Deposits','2014 Deposits','2015 Deposits','2016 Deposits']]

In [96]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Column Selectors

In [97]:
cat_selector = make_column_selector(dtype_include='object')
num_selector = make_column_selector(dtype_include ='number')

#column Transformer

In [98]:
freq_imputer = SimpleImputer(strategy='most_frequent')
mean_imputer = SimpleImputer(strategy='mean_imputer')

In [99]:
scaler = StandardScaler()
ohe = OneHotEncoder(handle_unknown='ignore')

# Preprocessing

In [100]:
# Making a tuple for preprocessing for numerical column and numerical columns 
cat_tuple = (ohe, cat_selector)
num_tuple= (scaler, num_selector)

In [101]:
# make column transfomer
col_transformer = make_column_transformer(num_tuple, cat_tuple)

In [102]:
# used fot here for x_train
col_transformer.fit(X_train)

ColumnTransformer(transformers=[('standardscaler', StandardScaler(),
                                 <sklearn.compose._column_transformer.make_column_selector object at 0x7f7a1b0cdca0>),
                                ('onehotencoder',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 <sklearn.compose._column_transformer.make_column_selector object at 0x7f7a1b19d370>)])

#Pipelines

In [103]:
# numerci pipeline
numeric_pipe = make_pipeline(mean_imputer, scaler)
numeric_pipe

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='mean_imputer')),
                ('standardscaler', StandardScaler())])

In [104]:
# categrocal pipeline
categorical_pipe = make_pipeline(freq_imputer, ohe)
categorical_pipe

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))])

#Column Transfomer

In [105]:
# Tuple for the column transdomer 
number_tuple = (numeric_pipe, num_selector)
categorical_tuple = (categorical_pipe, cat_selector)

# ColumnTransformer
preprocessor = make_column_transformer(number_tuple, categorical_tuple)
preprocessor

ColumnTransformer(transformers=[('pipeline-1',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='mean_imputer')),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 <sklearn.compose._column_transformer.make_column_selector object at 0x7f7a1b0cdca0>),
                                ('pipeline-2',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 <sklearn.compose._column_transformer.make_column_selector object at 0x7f7a1b19d370>)])

In [106]:
X_train_processed = col_transformer.transform(X_train)
X_test_processed = col_transformer.transform(X_test)

In [107]:
 X.head()

,Institution Name,Main Office,City,Branch Number,Established Date,Acquired Date,Branch Name,Street Address,County,State,Zipcode,Latitude,Longitude,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
0,JPMorgan Chase Bank,1,Columbus,0,01/01/1824,NaN,JPMorgan Chase Bank Main Office,1111 Polaris Parkway,Delaware,OH,43240,40.14453,-82.99115,633131000.0,743268000.0,832455000.0,916543000.0,1.032549e+09,1.069425e+09,1155185000
1,JPMorgan Chase Bank,0,Scarsdale,2,03/20/1961,NaN,Vernon Hills Scarsdale Branch,676 White Plains Road,Westchester,NY,10583,40.97008,-73.80670,293229.0,310791.0,325742.0,327930.0,3.277920e+05,3.414750e+05,381558
2,JPMorgan Chase Bank,0,Great Neck,3,09/09/1963,NaN,Great Neck Northern Boulevard Branch,410 Northern Boulevard,Nassau,NY,11021,40.77944,-73.72240,191011.0,206933.0,216439.0,237983.0,2.341830e+05,2.624550e+05,278940
3,JPMorgan Chase Bank,0,Hartsdale,4,02/19/1966,NaN,North Hartsdale Branch,353 North Central Avenue,Westchester,NY,10530,41.02654,-73.79168,87110.0,88367.0,93163.0,109659.0,1.119850e+05,1.167720e+05,140233
4,JPMorgan Chase Bank,0,Lawrence,5,01/16/1965,NaN,Lawrence Rockaway Branch,335 Rockaway Turnpike,Nassau,NY,11559,40.62715,-73.73675,172608.0,172749.0,189413.0,198445.0,2.051980e+05,2.232000e+05,235594